# Brief Checklist

## .Devcontainer

If you use this with `.devcontainer`, everything should just work like magic.
Make sure that the kernel (the thing on the top right) says `python-project-start (3.12.11) (Python 3.12.11)`.

## Without .Devcontainer

Well, you should not. But if you want to skip using `Docker` for just a short period of time, you can set up your environment manually.
I will no longer help people who use this in ML class if you don't have a good reason.

Before you use this, create a `virtual environment` and pin thehon version using the following command.

```sh
uv sync
```

reopen this file.

then, select the kernel that point to the root `.venv` folder.

In [1]:
# try run this.
# If this does not run, fix it first
print("Hello World")

Hello World

# Path referencing

Look at the `explorer`. There is a folder named `data`.
Let's agree that we will put our data over there.

I have put `example.csv` in the `data` folder.

*Note: All files in `/data` are ignored in `.gitignore` except `.keeps` and `example.csv`.*

In [2]:
import pandas as pd


pd.read_csv("../data/example.csv") # type:ignore

   col1  col2  col3
0     1     2     3
1    11    22    33
2   111   222   333

Notice that I have to refer the data with `../data/example.csv`.

This is file referencing using relative path.

Relative to what? Relative to this jupyter notebook file.

`..` means parent directory.

So, with `../` it refer to the parent of the directory of this jupyter notebook file.

Then, we further reference the file path as if we are at the root directory with `data/example.csv`.

If I have to break this down to a variable, it is like this.

In [3]:
# This is my current path
!pwd

/Projects/python-project-starter/notebooks

In [4]:
import os
ROOT_DIR = "/Projects/python-project-starter"
DATA_DIR = "data"
CSV_PATH = "example.csv"

print(os.path.join(ROOT_DIR, DATA_DIR, CSV_PATH))

pd.read_csv(os.path.join(ROOT_DIR, DATA_DIR, CSV_PATH)) # type:ignore

/Projects/python-project-starter/data/example.csv

   col1  col2  col3
0     1     2     3
1    11    22    33
2   111   222   333

# Assigment

Change the following variable to your name and student account, save, and push the changes.

In [5]:
name:str = ""
student_id:str = "st"
print(f"{student_id} - {name}")

st -

In [6]:
import python_project_starter

OSError: Missing 'LOG_DIR' in environment variable